# Aimons
AQUARDER = 'Aquarder'
FIRESOR = 'Firesor'
ELECTDER = 'Electder'
MOUSEBUG = 'Mousebug'
SPLAT = 'Splant'
ROCKDOG = 'Rockdog'

# Tipos de Habilidades
NORMAL = 'Normal'
POTENCIADOR = 'Potenciador'

# Habilidades de Aimons
AQUAJET = 'Aqua-jet'
COLAFERREA = 'Cola Férrea'
CABEZAZO = 'Cabezazo'
LLUVIA = 'Lluvia'
LLAMARADA = 'Llamarada'
EMBESTIDA = 'Embestida'
MORDISCO = 'Mordisco'
DIASOLEADO = 'Día Soleado'
TRUENO = 'Trueno'
ARANAZO = 'Arañazo'
CAMPOMAGNETICO = 'Campo Magnético'
PICOTAZO = 'Picotazo'
ESPORAS = 'Esporas'
HOJANAVAJA = 'Hoja Navaja'
RAYOSOLAR = 'Rayo Solar'
ROCAAFILADA = 'Roca Afilada'
VELOCIDAD = 'Velocidad'
CAMPOROCAS = 'Campo de Rocas'

# Tipos de Aimons'
AGUA = 'Agua'
FUEGO = 'Fuego'
ELECTRICO = 'Eléctrico'
ESCARABAJO = 'Escabajo'
PLANTA = 'Planta'
ROCA = 'Roca'
